#! /usr/bin/env python

import codecs
import datetime
import os
import parse

def generate_page(feed_url, outpath):
    "Renders the contents of an RSS feed into the given HTML file."
    tree = parse.tree_from_url(feed_url)
    if os.path.exists(outpath):
        os.remove(outpath)
    with codecs.open(outpath, 'a', 'utf-8') as f:
        write_preamble(f, feed_url)
        write_header(f, parse.header_data(tree))
        write_items(f, parse.items(tree))
        write_conclusion(f)

def write_preamble(f, feed_url):
    f.write('<html><head><title>Feed Summary for %s</title></head><body>' % feed_url)

def write_header(f, header_tags):
    title, link, desc = header_tags
    f.write('<h1><a href="%s">%s</a></h1>' % (link, title))
    f.write('<p>%s</p>' % desc)

def write_items(f, items):
    for item in items:
        f.write('<hr />')
        desc = item['description']
        title = item['title']
        if 'url' in item:
            url = item['url']
            f.write('<h2><a href="%s">%s</a></h2>' % (url, title))
        else:
            f.write('<h2>%s</h2>' % title)
        f.write(desc)

    
def write_conclusion(f):
    f.write('<hr />')
    f.write('<footer>Generated by Feed Reader v0.1 on %s.</footer>' % datetime.date.today())
    f.write('</body><html>')
        
    
def main():
    generate_page('http://www.feedforall.com/blog-feed.xml', '/home/nadeem/tmp/feed.html')
    generate_page('http://cyber.law.harvard.edu/rss/examples/rss2sample.xml',
                  '/home/nadeem/tmp/feed2.html')
    generate_page('http://www.feedforall.com/sample.xml', '/home/nadeem/tmp/feed3.html')
    generate_page('http://www.feedforall.com/sample-feed.xml', '/home/nadeem/tmp/feed4.html')

if __name__ == '__main__':
    main()
